spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_2
    username: postgres
    password: password123
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true